import { AI_CONTRACT } from './contract.js';
import { SKILL_SPECS } from './skills.js';
import type { ToolDef } from '../adapters/index.js';
import { getTool, ruleFilesFor } from '../adapters/index.js';
import type { ProjectFacts } from '../core/project.js';

export interface BootstrapContext {
  facts: ProjectFacts;
  tools: ToolDef[];
  /** Free-form team norms the user typed in (`engram init --notes "..."`). */
  notes?: string;
  /** Project-specific notes already living in the repo. */
  extra?: string;
}

const bullets = (items: string[]): string => items.map((i) => `- ${i}`).join('\n');

/**
 * The meta-prompt: handed to whatever AI assistant the user is currently talking to, it produces
 * tool-idiomatic rule files for THIS project instead of generic boilerplate.
 */
export function buildBootstrapPrompt(ctx: BootstrapContext): string {
  const { facts, tools } = ctx;
  const files = ruleFilesFor(tools.map((t) => t.id));
  const f = facts;

  const factsBlock = [
    `- Project name: \`${f.name}\``,
    `- Root: \`${f.root}\``,
    `- Detected stack: ${f.stack.length ? f.stack.map((s) => `\`${s}\``).join(', ') : '_(none detected)_'}`,
    `- Top-level directories: ${f.dirs.length ? f.dirs.map((d) => `\`${d}/\``).join(', ') : '_(none)_'}`,
    `- npm scripts: ${f.scripts.length ? f.scripts.map((s) => `\`${s}\``).join(', ') : '_(none)_'}`,
    `- Git repository: ${f.hasGit ? 'yes' : 'no'}`,
  ].join('\n');

  // Presence of an engram-managed rule file is a side effect of `init` itself, so reporting it as
  // a project fact would make the meta-prompt differ between runs. What actually matters is the
  // rule: never overwrite an existing body.
  const ruleFileAdvice = facts.existingRuleFiles.length
    ? `- Rule files already present: ${facts.existingRuleFiles.map((p) => `\`${p}\``).join(', ')} — edit the existing file, never recreate it.`
    : '- No AI rule file exists yet: create them.';

  const perTool = tools
    .map((tool) => {
      const toolFiles = files
        .filter((x) => tool.ruleFiles.some((rf) => rf.path === x.def.path))
        .map((x) => {
          const others = tools
            .filter((o) => o.id !== tool.id && o.ruleFiles.some((rf) => rf.path === x.def.path))
            .map((o) => o.id);
          const shared = others.length ? ` (also read by: ${others.join(', ')})` : '';
          const imports = x.def.imports?.length ? `\n   Imports: ${x.def.imports.join(' ')}` : '';
          return `   - \`${x.def.path}\`${shared}\n     Purpose: ${x.def.note}${imports}`;
        })
        .join('\n');

      const skills = tool.skillSinks.length
        ? bullets(
            tool.skillSinks.map(
              (s) =>
                `\`${s.dir}/\` — ${s.kind === 'agent-skills' ? 'one `SKILL.md` per skill' : s.kind === 'prompt-toml' ? 'one `.toml` command per skill' : 'one `.md` slash command per skill'}${s.note ? ` (${s.note})` : ''}`,
            ),
          )
        : '- _(no project-scoped skill support; the contract block is the fallback)_';

      return [
        `### \`${tool.id}\` — ${tool.label}`,
        '',
        `Write:`,
        toolFiles,
        '',
        `Skill carrier:`,
        skills,
        '',
        `Style rules for this tool:`,
        tool.styleGuide,
      ].join('\n');
    })
    .join('\n\n');

  const skillTable = SKILL_SPECS.map(
    (s) => `| \`/${s.name}\` | \`.ai/skills/${s.name}.md\` | ${oneLine(s.description.split('. Use')[0] ?? s.description)} |`,
  ).join('\n');

  const outputPaths = [...new Set(files.map((x) => x.def.path))].map((p) => `\`${p}\``).join(', ');

  return `# Bootstrap meta-prompt — author this project's AI rule files

> Generated by \`engram init\`. Paste everything below into your current AI coding assistant
> (Claude Code, Codex, Cursor, Pi, …), or save it and reference it. Then run \`engram sync\`.

## Role

You are the staff engineer who has just joined **${f.name}**. You are writing the AI rule files
(${outputPaths}) for this specific repository, for the tools listed below. Your output replaces
generic boilerplate: every claim must be checkable against this codebase.

## Project facts (already detected — verify, do not trust blindly)

${factsBlock}
${ruleFileAdvice}
${ctx.notes ? `\n## Team norms supplied by the user (must be honoured verbatim)\n\n${ctx.notes}\n` : ''}
${ctx.extra ? `\n## Extra project notes\n\n${ctx.extra}\n` : ''}
## What exists already: the memory bank

The repository contains \`.ai/\` — a portable memory bank that every tool shares.
Read \`.ai/README.md\` and \`.ai/ARCHITECTURE.md\` before writing anything; they are the source of
truth for stack and boundaries. Memory files you must know how to use:

${skillTable}

## Task

For **each** tool section below, write or update that tool's rule file(s) so that:

1. **Commands are real.** Run or read \`package.json\`/Makefile/CI config; every command you state
   must work in this repository today. Include how to run a single test file.
2. **Conventions are specific.** Naming, error handling, layering, forbidden operations, secrets
   handling, commit/PR expectations — drawn from how this code actually looks, not from generic
   "best practices". Where the repo is inconsistent, say so in one line instead of inventing a rule.
3. **Scope is bounded.** Keep the file small enough to be followed (the per-tool limit is in its
   section). Depth goes into \`.ai/\`, not into the rule file.
4. **The memory contract is preserved.** The file already ends with this block, delimited by
   \`<!-- engram:contract:start -->\` / \`<!-- engram:contract:end -->\`:

${indent(AI_CONTRACT, 4)}

   **Rules for you about that block:** write *only* the content above the block. Never edit,
   reword, move or delete it — \`engram sync\` regenerates it and would overwrite your version.
5. **Placeholders are gone.** Remove the \`engram:todo\` block and write real content in its place.

${perTool}

## Method

1. Read the code first: entry points, one vertical slice end to end, the test suite, CI config.
2. Read \`.ai/ARCHITECTURE.md\` and the newest \`.ai/decisions/\` entries; do not contradict them.
3. Write the rule file body per tool. When two tools share a file (e.g. \`AGENTS.md\`), write it
   once so it works for every reader of that file.
4. Finish by running the verification commands you wrote down, and report anything that failed.

## Output format

For each file: a one-paragraph summary of what you encoded and why, then the file path. End with a
short list of "assumptions I made that a human should check".

Then tell the user to run:

\`\`\`bash
engram sync     # refreshes the contract block and re-materialises skill files
engram dump     # ≤1.5 KB fingerprint to paste into the next session
\`\`\`
`;
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .trim()
    .split('\n')
    .map((l) => pad + l)
    .join('\n');
}

function oneLine(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

/** Short per-tool summary printed at the end of `init`. */
export function toolSummary(tools: ToolDef[]): string {
  return tools
    .map((t) => {
      const paths = t.ruleFiles.map((f) => f.path).join(', ');
      const shared = paths.includes('AGENTS.md') ? ' (shared with other AGENTS.md tools)' : '';
      return `  ${t.id.padEnd(10)} ${paths}${shared}`;
    })
    .join('\n');
}

export { getTool };