import path from 'node:path';
import { promises as fs } from 'node:fs';
import { SKILL_SPECS } from '../templates/skills.js';
import { RETIRED_SINK_DIRS, type ToolDef, type SkillSink } from '../adapters/index.js';
import { pathExists, readFileSafe, listIfPresent } from '../core/project.js';

/**
 * Remove generated carriers that no longer have a canonical skill behind them.
 *
 * Two cases, one rule: **only a file engram itself generated is ever deleted.**
 *
 * 1. A sink directory engram retired (`.pi/skills`): the four copies engram used to write are
 *    orphans in every repository that ever ran `sync`.
 * 2. A skill the project deleted from `.ai/skills/`. Without this, `sync` refreshed the surviving
 *    carriers and left the deleted one advertising itself to the tool forever — the tool then
 *    offers a `/skill` command whose canonical spec is gone, and nothing reports it.
 *
 * Hand-written files are out of reach: `research/.agents/skills/net-access/SKILL.md` carries no
 * generated header, so a project-owned skill sitting in a carrier directory survives every sync.
 * `.ai/` is never a carrier dir, so the canonical bank cannot be touched here at all.
 */

/**
 * The generated header, matched as a **whole line** — never as a substring.
 *
 * `content.includes('<!-- engram:generated -->')` looked equivalent and was not: a hand-written
 * carrier whose prose *mentions* the marker — a `.claude/skills/engram-notes/SKILL.md` explaining
 * how carriers are stamped, say — was classified as generated and deleted, which is the exact
 * opposite of what the docstring above promises. Requiring the rest of the stamp (`generated by
 * engram from <path>`) means even a quoted line does not qualify.
 */
const GENERATED_HEADER_RE = /^<!-- engram:generated --> generated by engram from \S+/m;

async function isGeneratedCarrier(root: string, rel: string): Promise<boolean> {
  const content = await readFileSafe(path.join(root, rel));
  return content !== null && GENERATED_HEADER_RE.test(content);
}

/**
 * Resolve a path and confirm it is still inside the project root.
 *
 * `pathExists`, `readFileSafe` and `fs.rm` all follow symlinks, so a symlinked carrier directory
 * pointing outside the repository let pruning delete a file engram never created. The *parent*
 * directory is what gets resolved — the leaf is the file being tested, and on some paths it may not
 * exist yet.
 */
async function resolvesInside(root: string, rel: string): Promise<boolean> {
  try {
    const realRoot = await fs.realpath(root);
    const realParent = await fs.realpath(path.dirname(path.join(root, rel)));
    return realParent === realRoot || realParent.startsWith(realRoot + path.sep);
  } catch {
    // Unresolvable (missing parent, ELOOP, EACCES): treat as unsafe rather than guess.
    return false;
  }
}

/** Carrier paths the given tools write. A dir in here is never treated as retired. */
function ownedDirs(tools: ToolDef[]): Set<string> {
  return new Set(tools.flatMap((t) => t.skillSinks.map((s) => s.dir)));
}

async function removeIfEmpty(dir: string): Promise<void> {
  try {
    const entries = await fs.readdir(dir);
    if (entries.length === 0) await fs.rmdir(dir);
  } catch {
    // A non-empty or already-gone directory is the normal case.
  }
}

export interface PruneResult {
  /** Carrier paths that were removed, project-relative. */
  removed: string[];
}

/** Every generated carrier file present in one sink directory, including nested `SKILL.md`. */
async function carriersIn(root: string, sink: SkillSink): Promise<string[]> {
  const abs = path.join(root, sink.dir);
  const listing = await listIfPresent(abs);
  const out = listing.names.map((entry) => path.posix.join(sink.dir, entry));
  if (sink.kind !== 'agent-skills') return out;
  // `agent-skills` also nests `<name>/SKILL.md`; a file listing alone cannot see it.
  try {
    for (const dirent of await fs.readdir(abs, { withFileTypes: true })) {
      if (dirent.isDirectory()) out.push(path.posix.join(sink.dir, dirent.name, 'SKILL.md'));
    }
  } catch {
    /* absent or unreadable: nothing to prune */
  }
  return out;
}

/** The skill name a carrier path was generated for, or null when the shape is unrecognised. */
function nameOfCarrier(sink: SkillSink, rel: string): string | null {
  const base = path.posix.basename(rel);
  if (sink.kind === 'agent-skills') {
    return base === 'SKILL.md' ? path.posix.basename(path.posix.dirname(rel)) : base.replace(/\.md$/, '');
  }
  if (sink.kind === 'prompt-md-args') {
    const prefix = sink.prefix ?? '';
    const suffix = sink.suffix ?? '.md';
    if (!base.startsWith(prefix) || !base.endsWith(suffix)) return null;
    return base.slice(prefix.length, base.length - suffix.length);
  }
  return base.replace(/\.toml$/, '');
}

/**
 * Remove generated carriers whose canonical skill is gone, plus everything left behind in a
 * retired sink directory. Returns the removed paths; never touches a file it did not generate.
 *
 * `canonicalNames` being empty is **not** treated as "no skills exist, delete everything". An empty
 * list can also mean the caller could not read the canonical directory — a missing `.ai/skills/`, a
 * `--root` typo, a bank mid-move, an unreadable directory — and in that state deleting every
 * carrier is the worst available guess. When the canonical directory is gone the carriers are the
 * *only* copy of each skill body, so the loss is real and unrecoverable.
 *
 * That is why the signature demands an explicit `skillsDirAuthoritative` rather than inferring
 * intent from a count. A default of `true` is deliberately the *unsafe* value: every caller must
 * state the precondition, and the compiler makes it awkward to forget.
 */
export async function pruneStaleCarriers(
  root: string,
  tools: ToolDef[],
  canonicalNames: readonly string[],
  options: { dryRun?: boolean; skillsDirAuthoritative?: boolean } = {},
): Promise<PruneResult> {
  const { dryRun = false, skillsDirAuthoritative = false } = options;
  const owned = ownedDirs(tools);
  const removed: string[] = [];
  const canonical = new Set(canonicalNames);
  // Without a readable canonical directory there is no authority to declare a carrier an orphan.
  const pruneOrphans = skillsDirAuthoritative;

  // 1. Retired sink dirs: only engram's own built-in skill names were ever written there.
  for (const dir of RETIRED_SINK_DIRS) {
    if (owned.has(dir)) continue;
    let touched = false;
    for (const spec of SKILL_SPECS) {
      const candidates = [
        path.posix.join(dir, spec.name, 'SKILL.md'),
        path.posix.join(dir, `${spec.name}.md`),
        path.posix.join(dir, `${spec.name}.toml`),
      ];
      for (const candidate of candidates) {
        if (!(await pathExists(path.join(root, candidate)))) continue;
        if (!(await resolvesInside(root, candidate))) continue;
        if (!(await isGeneratedCarrier(root, candidate))) continue;
        if (!dryRun) await fs.rm(path.join(root, candidate));
        removed.push(candidate);
        touched = true;
        if (!dryRun && candidate.endsWith('SKILL.md')) await removeIfEmpty(path.join(root, dir, spec.name));
      }
    }
    if (touched && !dryRun) await removeIfEmpty(path.join(root, dir));
  }

  // 2. Orphans in the sinks the selected tools do own: a carrier whose canonical spec is gone.
  //    Enumerating the directory (not a name list) is what catches a skill deleted outright —
  //    its name is not in any list this process was handed.
  if (pruneOrphans) {
    for (const tool of tools) {
      for (const sink of tool.skillSinks) {
        for (const rel of await carriersIn(root, sink)) {
          const name = nameOfCarrier(sink, rel);
          if (!name || canonical.has(name)) continue;
          if (!(await resolvesInside(root, rel))) continue;
          if (!(await isGeneratedCarrier(root, rel))) continue;
          if (!dryRun) await fs.rm(path.join(root, rel));
          removed.push(rel);
          if (!dryRun && rel.endsWith('SKILL.md')) await removeIfEmpty(path.join(root, sink.dir, name));
        }
      }
    }
  }

  return { removed: [...new Set(removed)] };
}
