import {
  AI_CONTRACT,
  CONTRACT_END,
  CONTRACT_START,
  GENERATED_MARKER,
  MANAGED_MARKER,
  withContract,
  withoutContract,
} from '../templates/contract.js';
import type { RuleFileDef, RuleFileKind } from './index.js';

export interface RuleRenderContext {
  projectName: string;
  /** Sibling tools sharing the same file, e.g. AGENTS.md → codex, pi. */
  alsoReadBy: string[];
}

const TODO_BLOCK = (projectName: string): string => `# ${projectName} — agent instructions

<!-- engram:todo v1 -->
**This section is a placeholder.** Open \`.engram/BOOTSTRAP.md\` and let your AI assistant author
this file for your real project (stack, commands, conventions, boundaries), then delete this block.

A good replacement contains, in this order:
1. Build / run / test commands, copy-pasteable, with how to run a single test.
2. Directory map with one line of responsibility each.
3. Hard conventions: naming, error handling, forbidden operations.
4. Definition of done: what must pass before a change is considered complete.
<!-- /engram:todo -->`;

const CLAUDE_IMPORTS = [
  '@.ai/README.md',
  '',
  '> The two files above are the memory contract; they are pointers, not background reading.',
];

function frontmatterFor(def: RuleFileDef): string {
  switch (def.kind) {
    case 'cursor':
      return ['---', 'description: Project memory contract and workflow rules', 'globs: **/*', 'alwaysApply: true', '---', ''].join('\n');
    case 'windsurf':
      return ['---', 'trigger: always_on', 'description: Project memory contract (.ai/) and working rules', '---', ''].join('\n');
    case 'copilot':
      if (def.path.includes('/instructions/')) {
        return ['---', 'applyTo: "**"', '---', ''].join('\n');
      }
      return '';
    default:
      return '';
  }
}

/** Body a human (or their AI assistant) is expected to replace, without the contract. */
export function ruleBodyPlaceholder(projectName: string): string {
  return TODO_BLOCK(projectName);
}

/**
 * Render a full rule file: frontmatter + authored body + the engram contract.
 * `existing` content is preserved when present, and only the contract block is refreshed.
 */
export function renderRuleFile(
  def: RuleFileDef,
  ctx: RuleRenderContext,
  existing?: string,
): string {
  const head = frontmatterFor(def);
  const shared =
    ctx.alsoReadBy.length > 0
      ? `\n\n_Read by: ${ctx.alsoReadBy.join(', ')}._\n`
      : '';
  const SHARED_LINE_RE = /^_Read by: .*_$/m;
const FRONTMATTER_RE = /^---\n[\s\S]*?\n---\n?/;
/** Only these tool formats have YAML frontmatter that must stay the very first bytes. */
const NEEDS_FRONTMATTER = new Set<RuleFileKind>(['cursor', 'windsurf', 'copilot']);

let body: string;
  if (existing && existing.trim()) {
    // Strip everything engram regenerates, so re-rendering never nests frontmatter,
    // shared-reader notes, the managed marker or the contract block.
    const stripped = existing
      .replace(NEEDS_FRONTMATTER.has(def.kind) ? FRONTMATTER_RE : /^$/, '')
      .replace(SHARED_LINE_RE, '')
      .replaceAll(MANAGED_MARKER, '');
    body = withoutContract(stripped);
  } else {
    const base = ruleBodyPlaceholder(ctx.projectName);
    body = def.kind === 'claude' ? `${base}\n\n${CLAUDE_IMPORTS.join('\n')}` : base;
  }
  const composed = head ? `${head}${body}${shared}` : `${body}${shared}`;
  // The marker goes after frontmatter (Cursor/Windsurf need it first) but before the contract.
  return withContract(`${composed.trim()}\n\n${MANAGED_MARKER}`);
}

/** Re-render only the contract block of an existing file (used by `engram sync`). */
export function refreshContract(existing: string, def: RuleFileDef): string {
  if (!existing.includes(CONTRACT_START)) {
    const head = frontmatterFor(def);
    const base = existing.startsWith(head) && head ? existing.slice(head.length) : existing;
    return renderRuleFile(def, { projectName: 'this project', alsoReadBy: [] }, base);
  }
  const start = existing.indexOf(CONTRACT_START);
  const end = existing.indexOf(CONTRACT_END, start) + CONTRACT_END.length;
  return existing.slice(0, start) + `${CONTRACT_START}\n${AI_CONTRACT}${CONTRACT_END}` + existing.slice(end);
}

/** Header stamped on fully generated files (skill sinks) so they can be safely overwritten. */
export function generatedHeader(sourcePath: string): string {
  return `${GENERATED_MARKER} generated by engram from ${sourcePath} — do not edit; run \`engram sync\``;
}